NHL_TEAMS = {
    "ANA": "Anaheim Ducks",
    "BOS": "Boston Bruins",
    "BUF": "Buffalo Sabres",
    "CAR": "Carolina Hurricanes",
    "CBJ": "Columbus Blue Jackets",
    "CGY": "Calgary Flames",
    "CHI": "Chicago Blackhawks",
    "COL": "Colorado Avalanche",
    "DAL": "Dallas Stars",
    "DET": "Detroit Red Wings",
    "EDM": "Edmonton Oilers",
    "FLA": "Florida Panthers",
    "LAK": "Los Angeles Kings",
    "MIN": "Minnesota Wild",
    "MTL": "Montreal Canadiens",
    "NJD": "New Jersey Devils",
    "NSH": "Nashville Predators",
    "NYI": "New York Islanders",
    "NYR": "New York Rangers",
    "OTT": "Ottawa Senators",
    "PHI": "Philadelphia Flyers",
    "PIT": "Pittsburgh Penguins",
    "SEA": "Seattle Kraken",
    "SJS": "San Jose Sharks",
    "STL": "St. Louis Blues",
    "TBL": "Tampa Bay Lightning",
    "TOR": "Toronto Maple Leafs",
    "UTA": "Utah Hockey Club",
    "VAN": "Vancouver Canucks",
    "VGK": "Vegas Golden Knights",
    "WPG": "Winnipeg Jets",
    "WSH": "Washington Capitals"
}

NBA_TEAMS = {
    "ATL": "Atlanta Hawks",
    "BOS": "Boston Celtics",
    "BKN": "Brooklyn Nets",
    "CHA": "Charlotte Hornets",
    "CHI": "Chicago Bulls",
    "CLE": "Cleveland Cavaliers",
    "DAL": "Dallas Mavericks",
    "DEN": "Denver Nuggets",
    "DET": "Detroit Pistons",
    "GSW": "Golden State Warriors",
    "HOU": "Houston Rockets",
    "IND": "Indiana Pacers",
    "LAC": "Los Angeles Clippers",
    "LAL": "Los Angeles Lakers",
    "MEM": "Memphis Grizzlies",
    "MIA": "Miami Heat",
    "MIL": "Milwaukee Bucks",
    "MIN": "Minnesota Timberwolves",
    "NOP": "New Orleans Pelicans",
    "NYK": "New York Knicks",
    "OKC": "Oklahoma City Thunder",
    "ORL": "Orlando Magic",
    "PHI": "Philadelphia 76ers",
    "PHX": "Phoenix Suns",
    "POR": "Portland Trail Blazers",
    "SAC": "Sacramento Kings",
    "SAS": "San Antonio Spurs",
    "TOR": "Toronto Raptors",
    "UTA": "Utah Jazz",
    "WAS": "Washington Wizards"
}

MLB_TEAMS = {
    "ARI": "Arizona Diamondbacks",
    "ATL": "Atlanta Braves",
    "BAL": "Baltimore Orioles",
    "BOS": "Boston Red Sox",
    "CHC": "Chicago Cubs",
    "CHW": "Chicago White Sox",
    "CIN": "Cincinnati Reds",
    "CLE": "Cleveland Indians",
    "COL": "Colorado Rockies",
    "DET": "Detroit Tigers",
    "FLA": "Florida Marlins",
    "HOU": "Houston Astros",
    "KAN": "Kansas City Royals",
    "LAA": "Los Angeles Angels of Anaheim",
    "LAD": "Los Angeles Dodgers",
    "MIL": "Milwaukee Brewers",
    "MIN": "Minnesota Twins",
    "NYM": "New York Mets",
    "NYY": "New York Yankees",
    "OAK": "Oakland Athletics",
    "PHI": "Philadelphia Phillies",
    "PIT": "Pittsburgh Pirates",
    "SD": "San Diego Padres",
    "SF": "San Francisco Giants",
    "SEA": "Seattle Mariners",
    "STL": "St. Louis Cardinals",
    "TB": "Tampa Bay Rays",
    "TEX": "Texas Rangers",
    "TOR": "Toronto Blue Jays",
    "WAS": "Washington Nationals"
}

CBB_Teams = {
    "ALA": "Alabama",
    "AUB": "Auburn",
    "BOIS": "Boise State",
    "ASU": "Arizona State",
    "BAY": "Baylor",
    "BC": "Boston College",
    "ARIZ": "Arizona",
    "ARK": "Arkansas",
    "AKR": "Akron",
    "ALST": "Alabama State",
    "ALB": "Albany",
    "ALCN": "Alcorn State",
    "AMER": "American",
    "BALL": "Ball State",
    "BUFF": "Buffalo",
    "CAL": "California",
    "BGSU": "Bowling Green",
    "CIN": "Cincinnati",
    "CLEM": "Clemson",
    "DAY": "Dayton",
    "DEN": "Denver",
    "APP": "Appalachian State",
    "ARST": "Arkansas State",
    "BRWN": "Brown",
    "DEL": "Delaware",
    "BUT": "Butler",
    "CONN": "Connecticut",
    "CREI": "Creighton",
    "ECU": "East Carolina",
    "HOU": "Houston",
    "IU": "Indiana",
    "JAX": "Jacksonville",
    "MEM": "Memphis",
    "PITT": "Pittsburgh",
    "BRY": "Bryant",
    "BUCK": "Bucknell",
    "COLG": "Colgate",
    "COLO": "Colorado",
    "EKU": "Eastern Kentucky",
    "FAU": "Florida Atlantic",
    "FSU": "Florida State",
    "GONZ": "Gonzaga",
    "HARV": "Harvard",
    "IDHO": "Idaho",
    "ILL": "Illinois",
    "ISU": "Iowa State",
    "JMU": "James Madison",
    "KSU": "Kansas State",
    "KENT": "Kent State",
    "MARQ": "Marquette",
    "MD": "Maryland",
    "MIA": "Miami",
    "MICH": "Michigan",
    "MILW": "Milwaukee",
    "MINN": "Minnesota",
    "MIZ": "Missouri",
    "MISS": "Ole Miss",
    "PORT": "Portland",
    "AAMU": "Alabama A&M",
    "BEL": "Belmont",
    "BRAD": "Bradley",
    "DAV": "Davidson",
    "DRKE": "Drake",
    "DREX": "Drexel",
    "DUQ": "Duquesne",
    "EWU": "Eastern Washington",
    "FLA": "Florida",
    "FUR": "Furman",
    "ILST": "Illinois State",
    "KU": "Kansas",
    "KC": "Kansas City",
    "M-OH": "Miami of Ohio",
    "MSU": "Michigan State",
    "MORE": "Morehead State",
    "NEV": "Nevada",
    "OSU": "Ohio State",
    "OKST": "Oklahoma State",
    "ORE": "Oregon",
    "ORST": "Oregon State",
    "PSU": "Penn State",
    "PRIN": "Princeton",
    "PROV": "Providence",
    "PUR": "Purdue",
    "SDSU": "San Diego State",
    "ACU": "Abilene Christian",
    "AFA": "Air Force",
    "DART": "Dartmouth",
    "DEP": "DePaul",
    "EIU": "Eastern Illinois",
    "EVAN": "Evansville",
    "FRES": "Fresno State",
    "GW": "George Washington",
    "GT": "Georgia Tech",
    "GCU": "Grand Canyon",
    "HAMP": "Hampton",
    "IDST": "Idaho State",
    "INST": "Indiana State",
    "UK": "Kentucky",
    "MASS": "Massachusetts",
    "MORG": "Morgan State",
    "MUR": "Murray State",
    "NEB": "Nebraska",
    "NKU": "Northern Kentucky",
    "OAK": "Oakland",
    "OU": "Oklahoma",
    "RUTG": "Rutgers",
    "SF": "San Francisco",
    "TENN": "Tennessee",
    "TEX": "Texas",
    "TXST": "Texas State",
    "CARK": "Central Arkansas",
    "EMU": "Eastern Michigan",
    "FIU": "Florida International",
    "GTWN": "Georgetown",
    "UGA": "Georgia",
    "GRAM": "Grambling",
    "GB": "Green Bay",
    "HOW": "Howard",
    "LIB": "Liberty",
    "MONT": "Montana",
    "NIAG": "Niagara",
    "OMA": "Omaha",
    "PEPP": "Pepperdine",
    "RICH": "Richmond",
    "SC": "South Carolina",
    "SDST": "South Dakota State",
    "STAN": "Stanford",
    "SYR": "Syracuse",
    "TA&M": "Texas A&M",
    "TXSO": "Texas Southern",
    "TOL": "Toledo",
    "CLEV": "Cleveland State",
    "ETSU": "East Tennessee State",
    "FAIR": "Fairfield",
    "FGCU": "Florida Gulf Coast",
    "JKST": "Jackson State",
    "KENN": "Kennesaw State",
    "LEH": "Lehigh",
    "ME": "Maine",
    "MSST": "Mississippi State",
    "UNC": "North Carolina",
    "NDSU": "North Dakota State",
    "NIU": "Northern Illinois",
    "ODU": "Old Dominion",
    "PENN": "Pennsylvania",
    "SCST": "South Carolina State",
    "BU": "Boston University",
    "COLU": "Columbia",
    "FAMU": "Florida A&M",
    "GASO": "Georgia Southern",
    "GAST": "Georgia State",
    "MRSH": "Marshall",
    "MONM": "Monmouth",
    "ND": "Notre Dame",
    "ORU": "Oral Roberts",
    "SAC": "Sacramento State",
    "SDAK": "South Dakota",
    "TNST": "Tennessee State",
    "TLSA": "Tulsa",
    "VILL": "Villanova",
    "BING": "Binghamton",
    "CMU": "Central Michigan",
    "GMU": "George Mason",
    "LBSU": "Long Beach State",
    "LONG": "Longwood",
    "UL": "Louisiana",
    "MOST": "Missouri State",
    "UNM": "New Mexico",
    "NORF": "Norfolk State",
    "NU": "Northwestern",
    "URI": "Rhode Island",
    "SJSU": "San Jose State",
    "SEA": "Seattle",
    "STET": "Stetson",
    "TEM": "Temple",
    "TTU": "Texas Tech",
    "CIT": "The Citadel",
    "TULN": "Tulane",
    "UVA": "Virginia",
    "WAKE": "Wake Forest",
    "WASH": "Washington",
    "BELL": "Bellarmine",
    "COFC": "Charleston",
    "HPU": "High Point",
    "JVST": "Jacksonville State",
    "L-MD": "Loyola - Maryland",
    "MER": "Mercer",
    "UNH": "New Hampshire",
    "PAC": "Pacific",
    "RAD": "Radford",
    "SAM": "Samford",
    "SEMO": "Southeast Missouri State",
    "JOES": "St. Joseph's",
    "TOW": "Towson",
    "VT": "Virginia Tech",
    "WIS": "Wisconsin",
    "WYO": "Wyoming",
    "XAV": "Xavier",
    "COPP": "Coppin State",
    "LT": "Louisiana Tech",
    "NMSU": "New Mexico State",
    "PFW": "Purdue Fort Wayne",
    "SOU": "Southern",
    "USF": "South Florida",
    "AMCC": "Texas A&M - Corpus Christi",
    "UCSD": "UC San Diego",
    "WKU": "Western Kentucky",
    "CAM": "Campbell",
}

NFL_TEAMS = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GB": "Green Bay Packers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NE": "New England Patriots",
    "NO": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "LV": "Las Vegas Raiders",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "LAC": "Los Angeles Chargers",
    "SF": "San Francisco 49ers",
    "SEA": "Seattle Seahawks",
    "LAR": "Los Angeles Rams",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WAS": "Washington Commanders"
}

WNBA = {
    "ATL": "Atlanta Dream",
    "CHI": "Chicago Sky",
    "CON": "Connecticut Sun",
    "DAL": "Dallas Wings",
    "IND": "Indiana Fever",
    "LV": "Las Vegas Aces",
    "LAS": "Los Angeles Sparks",
    "MIN": "Minnesota Lynx",
    "NYL": "New York Liberty",
    "PHO": "Phoenix Mercury",
    "SEA": "Seattle Storm",
    "WAS": "Washington Mystics"
}


NCAAF = {
    "BC": "Boston College",
    "CLEM": "Clemson",
    "DUKE": "Duke",
    "FSU": "Florida State",
    "GT": "Georgia Tech",
    "LOU": "Louisville",
    "MIA": "Miami (FL)",
    "NCST": "NC State",
    "PITT": "Pittsburgh",
    "SYR": "Syracuse",
    "UNC": "North Carolina",
    "UVA": "Virginia",
    "VT": "Virginia Tech",
    "WAKE": "Wake Forest",
    "ILL": "Illinois",
    "IND": "Indiana",
    "IOWA": "Iowa",
    "MICH": "Michigan",
    "MSU": "Michigan State",
    "MINN": "Minnesota",
    "NEB": "Nebraska",
    "NW": "Northwestern",
    "OSU": "Ohio State",
    "PSU": "Penn State",
    "PUR": "Purdue",
    "RUTG": "Rutgers",
    "UMD": "Maryland",
    "WIS": "Wisconsin",
    "BAY": "Baylor",
    "ISU": "Iowa State",
    "KU": "Kansas",
    "KSU": "Kansas State",
    "OKLA": "Oklahoma",
    "OU": "Oklahoma",
    "OKST": "Oklahoma State",
    "TCU": "TCU",
    "TEX": "Texas",
    "TTU": "Texas Tech",
    "WVU": "West Virginia",
    "ARIZ": "Arizona",
    "ASU": "Arizona State",
    "CAL": "Cal",
    "COLO": "Colorado",
    "ORE": "Oregon",
    "UO": "Oregon",
    "ORST": "Oregon State",
    "STAN": "Stanford",
    "UCLA": "UCLA",
    "USC": "USC",
    "UTAH": "Utah",
    "WASH": "Washington",
    "UW": "Washington",
    "WSU": "Washington State"
}