ESPORT_LEAGUES = [
    "LOL", "CS2", "DOTA2", "VAL", "COD", "APEX", "R6"
]

LEAGUES = {
    # CS2
    "cs": "CS2",
    "csgo": "CS2",
    "counter-strike": "CS2",

    # League of Legends
    "league of legends": "LOL",
    "na lcs": "LOL",
    "lck": "LOL",
    "lcs": "LOL",
    'lec': "LOL",
    'lpl': "LOL",
    'eu lcs': "LOL",
    "leagueoflegends": "LOL",
    'lck challengers': "LOL",
    'lck challengers korea': "LOL",
    'riot': "LOL",

    # Valorant
    'valorant champions tour': "VAL",
    'valorant': "VAL",

    # COD
    "callofduty": "COD",

    # Dota2
    "dota": "DOTA2",
    'dota 2': "DOTA2",
    "dota pro circuit": "DOTA2",

    # Other Esports
    'apex legends global series': 'APEX',
    'r6 esports': 'R6',
    'rainbow six pro league': 'R6',
    'rl': "Rocket League",

    # Golf
    'pga tour': 'PGA',

    # Hockey
    "nhl1p": "NHL",
    "nhl2p": "NHL",
    "nhl3p": "NHL",

    # Baseball
    "mlbcombos": "MLB",

    # Tennis
    "tennis m": "ATP",
    "tennis w": "WTA",

    # Soccer
    "l1f": "LIGUE 1",
    "ligue1": "LIGUE 1",
    'llg': 'LA LIGA',
    'laliga': 'LA LIGA',
    'sea': 'SERIE A',
    'bun': 'BUNDESLIGA',
    "bundes": "BUNDESLIGA",
    'ser a': 'SERIE A',
    'seriea': 'SERIE A',
    'prem': 'EPL',
    "uel": "UEFA EUROPA",
    'ucl': "UEFA CHAMPIONS",
    'fifa': "SOCCER",
    "fifa world cup qualifiers": "FIFA",
    "fifa world cup qualifiers - uefa": "FIFA",

    # Basketball
    "nbap": "NBA",
    "nba preseason": "NBA",
    "nba1h": "NBA",
    "nba2h": "NBA",
    "euro": "EUROLEAGUE",
    "ncaab": "CBB",
    "ncaam": "CBB",
    "cbb2h": "CBB",

    # Football
    "cfb2h": "CFB",
    'cfb1h': 'CFB',
    'cfb1q': 'CFB',
    'cfb2q': 'CFB',
    'cfb3q': 'CFB',
    'cfb4q': 'CFB',
    'nfl2h': 'NFL',
    'nfl 2h': 'NFL',
    'nfl1h': 'NFL',
    'nfl 1h': 'NFL',
    'nfl1q': 'NFL',
    'nfl2q': 'NFL',
    'nfl3q': 'NFL',
    'nfl4q': 'NFL',
    "big 12": "CFB",
    "ncaaf": "CFB",
    "ncaafb": "CFB",

    # Futures
    # 'wnbasr': 'WNBA',
    # "nhlszn": 'NHL',
    # 'nbaszn': 'NBA',
    # 'nflszn': 'NFL',
    # "nhl futures": "NHL",
    # 'nba futures': 'NBA',

    # Fightning
    "mma": "UFC",
    "wba": "BOXING",


    # Other Sports
    'fia formula 2 championship': 'F2',
    "women's world cup": 'ICC',
    "the hundred (women)": "CRICKET",
    "tt": "TABLE TENNIS",
    "world grand prix": "DARTS",
    "eurogolf": "DP WORLD TOUR",
}

MARKET_TYPE_MAPPER = {
    "fg": "Full",
    "1h": "1H",
    "h1": "1H",
    "2h": "2H",
    "h2": "2H",
    "1q": "1Q",
    "q1": "1Q",
    "2q": "2Q",
    "q2": "2Q",
    "3q": "3Q",
    "q3": "3Q",
    "4q": "4Q",
    "q4": "4Q",
}

STAT_TYPES = {
    # Tennis
    "games played": "Total Games",
    "games won": "Total Games Won",
    "sets won": "Total Sets Won",
    "breakpts won": "Break Points Won",
    "match total games": "Total Games",

    # Football
    "pass tds": "Passing TDs",
    "passing td": "Passing TDs",
    'passing touchdowns': "Passing TDs",
    "pass touchdowns": "Passing TDs",
    "pass yards": "Passing Yards",
    "passing yds": "Passing Yards",
    "1st half passing yards": "1H Passing Yards",
    "passing yards + rushing yards": "Passing + Rushing Yards",
    "pass yards (combo)": "Passing Yards (Combo)",
    "receiving yds": "Receiving Yards",
    "rec yards": "Receiving Yards",
    "rush yards": "Rushing Yards",
    "rushing yds": "Rushing Yards",
    "rush tds": "Rushing TDs",
    "rushing touchdowns": "Rushing TDs",
    "rush+rec touchdowns": "Rushing + Receiving TDs",
    "rush+rec tds": "Rushing + Receiving TDs",
    "rush+rec td": "Rushing + Receiving TDs",
    "receiving + rushing touchdowns": "Rushing + Receiving TDs",
    "receiving yards + rushing yards": "Rushing + Receiving Yards",
    "rush + rec tds": "Rushing + Receiving TDs",
    "rush+rec yds": "Rushing + Receiving Yards",
    "rushing and receiving yards": "Rushing + Receiving Yards",
    "rush + rec yds": "Rushing + Receiving Yards",
    "rush + rec yards": "Rushing + Receiving Yards",
    "rush+rec yards": "Rushing + Receiving Yards",
    "rush+rec tds (combo)": "Rushing + Receiving TDs (Combo)",
    'completions in first 10 pass attempts': 'Completions In First 10 Passing Attempts',
    'fg made': "FG Made",
    "field goal made": "FG Made",
    "field goals made": "FG Made",
    'fg made (combo)': "FG Made (Combo)",
    'field goal yards': "FG Yards",
    'field goal yards (combo)': "FG Yards (Combo)",
    'halves with 100+ pass yards': "100+ Passing Yards in Each Half",
    'halves with 150+ pass yards': "150+ Passing Yards in Each Half",
    'halves with 25+ receiving yards': "25+ Receiving Yards in Each Half",
    'halves with 25+ rush yards': "25+ Rushing Yards in Each Half",
    'int': "Interceptions",
    'longest fg made yds (combo)': "Longest FG Made Yards (Combo)",
    'longest field goal made yds': "Longest FG Made Yards",
    'field goal long': "Longest FG Made Yards",
    'pass attempts': "Passing Attempts",
    'passing att': "Passing Attempts",
    'pass completions': "Passing Completions",
    "completions": "Passing Completions",
    'pass+rush yds': "Passing + Rushing Yards",
    "pass+rush yards": "Passing + Rushing Yards",
    "pass + rush yards": "Passing + Rushing Yards",
    "passing and rushing yards": "Passing + Rushing Yards",
    'pass + rush yds': "Passing + Rushing Yards",
    'pat made': "Passing Attempts Made",
    'quarters with 1+ reception': "1+ Receptions in Each Quarter",
    'quarters with 5+ receiving Yards': "5+ Receiving Yards in Each Quarter",
    'quarters with 5+ rec yards': "5+ Receiving Yards in Each Quarter",
    'quarters with 10+ rec yards': "10+ Receiving Yards in Each Quarter",
    'quarters with 10+ rush yards': "10+ Rushing Yards in Each Quarter",
    'quarters with 5+ rush yards': "5+ Rushing Yards in Each Quarter",
    'quarters with 25+ pass yards': "25+ Passing Yards in Each Quarter",
    'quarters with 50+ pass yards': "50+ Passing Yards in Each Quarter",
    'rec targets': "Receiving Targets",
    'targets': "Receiving Targets",
    'rush attempts': 'Rushing Attempts',
    "rushing att": 'Rushing Attempts',
    'rush yards in first 5 attempts': "Rushing Yards In First 5 Attempts",
    'shortest fg made yds (combo)': "Shortest FG Made Yards (Combo)",
    'shortest field goal made yds': "Shortest FG Made Yards",
    'tackles+ast': "Tackles + Assists",
    "tack+ast": "Tackles + Assists",
    "tackle assists": "Tackles + Assists",
    "solo+assist tackles": "Tackles + Assists",
    "tackles solo": "Solo Tackles",
    "tackles assisted": "Assists",
    'yards on first pass completion': "Total Yards On First Passing Completion",
    "yards on first reception": "Total Yards On First Reception",
    'yards on first rush attempt': "Total Yards On First Rushing Attempt",
    '1h pass tds': "1H Passing TDs",
    "first half passing yards": "1H Passing Yards",
    '1h pass yards': "1H Passing Yards",
    "first half receiving yards": "1H Receiving Yards",
    '1h rush yards': "1H Rushing Yards",
    '1h rush+rec tds': "1H Rushing + Receiving TDs",
    '1h rec yards': "1H Receiving Yards",
    "first quarter passing yards": "1Q Passing Yards",
    '1q pass tds': "1Q Passing TDs",
    '1q pass yards': "1Q Passing Yards",
    "first quarter rushing yards": "1Q Rushing Yards",
    '1q rush yards': "1Q Rushing Yards",
    '1q rush+rec tds': "1Q Rushing + Receiving TDs",
    "first quarter receiving yards": "1Q Receiving Yards",
    '1q rec yards': "1Q Receiving Yards",
    '25+ pass yards in each quarter': '25+ Passing Yards in Each Quarter',
    '25+ rec yards in each quarter': '5+ Receiving Yards in Each Quarter',
    '5+ rush yards in each quarter': '5+ Rushing Yards in Each Quarter',
    'defensive ints': "Defensive Interceptions",
    'interceptions (def)': "Defensive Interceptions",
    'fantasy points': 'Fantasy Score',
    'fantasy pts': 'Fantasy Score',
    'fantasy score (prizepicks)': 'Fantasy Score',
    "kicker fantasy points": 'Kicker Fantasy Score',
    "offensive fantasy points": "Offensive Fantasy Score",
    "kicker points": "Kicking Points",
    'first completion (yards)': "Yards On First Completion",
    'first drive receptions': 'Receptions On First Drive',
    'first reception (yards)': "Yards On First Reception",
    'first rush attempts': 'Rushing Attempts On First Drive',
    'first td scorer': '1st TD Scorer',
    "first touchdown": '1st TD Scorer',
    "last touchdown": "Last TD Scorer",
    'game high rec yards': "Game High Receiving Yards",
    "high receiving yards": "Game High Receiving Yards",
    'game high rush yards': "Game High Rushing Yards",
    "high rushing yards": "Game High Rushing Yards",
    'ints thrown': "Interceptions",
    "interceptions thrown": "Interceptions",
    'longest catch': "Longest Reception",
    "longest rush (yards)": "Longest Rush",
    "rush long": "Longest Rush",
    "longest reception (yards)": "Longest Reception",
    "rec long": "Longest Reception",
    'longest completion': "Longest Passing Completion",
    "longest pass completion": "Longest Passing Completion",
    'longest pass': 'Longest Passing Completion',
    "longest passing completion (yards)": "Longest Passing Completion",
    "touchdowns": "Anytime TD",
    "anytime touchdowns": "Anytime TD",
    "Kicker Extra Points": "XP Made",

    # Esports
    "kills in game 1": "Map 1 Kills",
    "game 1 kills": "Map 1 Kills",
    "game 2 kills": "Map 2 Kills",
    "kills on maps 1+2": "Maps 1-2 Kills",
    "kills in game 1+2": "Maps 1-2 Kills",
    "kills in maps 1+2": "Maps 1-2 Kills",
    "kills on maps 1+2+3": "Maps 1-3 Kills",
    "kills in maps 1+2+3": "Maps 1-3 Kills",
    "1st 2 maps kills": "Maps 1-2 Kills",
    "kills maps 1 2": "Maps 1-2 Kills",
    "1st 2 maps  kills": "Maps 1-2 Kills",
    "kills": "Maps 1-2 Kills", # Double Check its 1-2 for maps
    "1st 2 maps headshots": "Maps 1-2 Headshots",
    "headshots maps 1 2": "Maps 1-2 Headshots",
    "headshots on maps 1+2": "Maps 1-2 Headshots",
    "fantasy points in games 1+2": "Maps 1-2 Fantasy Score",
    "Fantasy Points on Maps 1+2": "Maps 1-2 Fantasy Score",
    "assists on maps 1+2": "Maps 1-2 Assists",
    "assists on maps 1+2+3": "Maps 1-3 Assists",
    "map 1-2 kills": "Maps 1-2 Kills",
    "map 1-2 headshots": "Maps 1-2 Headshots",

    # Darts
    "1st leg checkout total": "1st Leg Checkout Total",

    # Basketball
    "pts+asts": "Points + Assists",
    "pts+ast": "Points + Assists",
    "pts + asts": "Points + Assists",
    "points+assists": "Points + Assists",
    "points and assists": "Points + Assists",
    "pts+rebs": "Points + Rebounds",
    "pts+reb": "Points + Rebounds",
    "pts + rebs": "Points + Rebounds",
    "pts+rebs+asts": "Points + Rebounds + Assists",
    "pts+reb+asts": "Points + Rebounds + Assists",
    "pts+reb+ast": "Points + Rebounds + Assists",
    "pts + rebs + asts": "Points + Rebounds + Assists",
    "pts reb ast": "Points + Rebounds + Assists",
    "points+rebounds+assists": "Points + Rebounds + Assists",
    "points+rebounds": "Points + Rebounds",
    "points and rebounds": "Points + Rebounds",
    "rebs+asts": "Rebounds + Assists",
    "reb+ast": "Rebounds + Assists",
    "rebs + asts": "Rebounds + Assists",
    "rebounds+assists": "Rebounds + Assists",
    "rebounds and assists": "Rebounds + Assists",
    "assists + rebounds": "Rebounds + Assists",
    "3pm per game avg": "3-Pt Made Per Game Avg",
    "3pt made": "3-Pt Made",
    "3-pointers made": "3-Pt Made",
    "3 pointers made": "3-Pt Made",
    "three pointers": "3-Pt Made",
    "made threes": "3-Pt Made",
    "threes made": "3-Pt Made",

    # Baseball
    "1+2+3 inning hitter fantasy score": "1+2+3 Inning Batter Fantasy Score",
    "1+2+3+4+5 inning hitter fantasy score": "1+2+3+4+5 Inning Batter Fantasy Score",
    "1+2+3 inning hits+runs+rbis": "1+2+3 Inning Hits + Runs + RBIs",
    "1+2+3+4+5 inning hits+runs+rbis": "1+2+3+4+5 Inning Hits + Runs + RBIs",
    "1-3 inn. runs allowed": "1+2+3 Inning Runs Allowed",
    "1st inning hits allowed": "1st Inning Hits Allowed",
    "1st inn. hits allowed": "1st Inning Hits Allowed",
    "1st inn. pitch count": "1st Inning Pitches Thrown",
    "first inning runs": "1st Inning Runs Allowed",
    "1st inning runs allowed": "1st Inning Runs Allowed",
    "1st inn. runs allowed": "1st Inning Runs Allowed",
    "1st inning pitcher strikeouts": "1st Inning Pitcher Strikeouts",
    "1st inn. strikeouts": "1st Inning Pitcher Strikeouts",
    "1st inning hits+runs+rbis": "1st Inning Hits + Runs + RBIs",
    "1st inning hitter fantasy score": "1st Inning Batter Fantasy Score",
    "1st inning pitches thrown": "1st Inning Pitches Thrown",
    "1st inning walks allowed": "1st Inning Walks Allowed",
    "1st inn. batters faced": "1st Inning Batters Faced",
    "hits+runs+rbis": "Hits + Runs + RBIs",
    "h+r+rbi": "Hits + Runs + RBIs",
    "hits + runs + rbis": "Hits + Runs + RBIs",
    "hits runs rbis": "Hits + Runs + RBIs",
    "rbis": "RBIs",
    "runs batted in": "RBIs",
    "player runs": "Runs",
    "hitter strikeouts": "Batter Strikeouts",
    "hitter fantasy score": "Fantasy Score",
    "fantasy points, batter fantasy points": "Fantasy Score",
    "fantasy points, pitching fantasy points": "Fantasy Score",
    "fantasy score (parlayplay)": "Fantasy Score",
    "batter fantasy points": "Fantasy Score",
    "walks": "Batter Walks",
    "batting walks": "Batter Walks",
    "bat walks": "Batter Walks",
    "strikeouts": "Pitcher Strikeouts",
    "strikeouts thrown": "Pitcher Strikeouts",
    "so (thrown)": "Pitcher Strikeouts",
    "pitching k": "Pitcher Strikeouts",
    "pitching strikeouts": "Pitcher Strikeouts",
    "pitching bb": "Walks Allowed",
    "pitching er": "Earned Runs Allowed",
    "earned runs": "Earned Runs Allowed",
    "pitcher earned runs": "Earned Runs Allowed",
    "batter strikeouts": "Batter Strikeouts",
    "batting strikeouts": "Batter Strikeouts",
    "pitcher outs": "Pitching Outs",
    "pitcher total outs": "Pitching Outs",
    "outs": "Pitching Outs",
    "total bases (hits only)": "Total Bases",
    "total bases (from hits)": "Total Bases",
    "bases": "Total Bases",
    "pitches": "Total Pitches",
    "pitcher walks": "Walks Allowed",
    "pitching walks": "Walks Allowed",
    "hits against": "Hits Allowed",
    "pitching hits": "Hits Allowed",

    # Hockey
    "goals allowed": "Goals Against",
    "goalie saves": "Saves",

    # Other Sports
    "first leg checkout": "1st Leg Checkout Total",
    "first set 180's": "1st Set 180s",
    "match 180s": "180s Thrown",

    # Futures
    "regular season assists per game average": "Assists Per Game Avg",
    "regular season points per game average": "Points Per Game Avg",
    "regular season rebounds per game average": "Rebounds Per Game Avg",
}


