LEAGUES = {
    "cs": "CS2",
    "counter-strike": "CS2",
    "league of legends": "LOL",
    "dota": "DOTA2",
    'dota 2': "DOTA2",
    "dota pro circuit": "DOTA2",
    "lck": "LOL",
    "lcs": "LOL",
    'lec': "LOL",
    'lpl': "LOL",
    'wnbasr': 'WNBA',
    'pga tour': 'PGA',
    'apex legends global series': 'APEX',
    'r6 esports': 'R6',
    'rainbow six pro league': 'R6',
    'fia formula 2 championship': 'F2',
    "leagueoflegends": "LOL",
    'valorant champions tour': "VAL",
    'valorant': "VAL",
    'eu lcs': "LOL",
    "mlbcombos": "MLB",
    "big 12": "CFB",
    "ncaaf": "CFB",
    "ncaafb": "CFB",
    "tennis m": "ATP",
    "tennis w": "WTA",
    "l1f": "LIGUE 1",
    'llg': 'LA LIGA',
    'sea': 'SERIE A',
    'bun': 'BUNDESLIGA',
    "bundes": "BUNDESLIGA",
    'ser a': 'SERIE A',
    'prem': 'EPL',
    'ucl': "UEFA CHAMPIONS",
    "the hundred (women)": "CRICKET",
    'lck challengers': "LOL",
    'lck challengers korea': "LOL",
    "nbap": "NBA",
    "cfb2h": "CFB",

}

MARKET_TYPE_MAPPER = {
    "fg": "Full"
}

STAT_TYPES = {
    ################## Baseketball ##################
    "first_qtr_points": "1q points",
    "first_qtr_assists": "1q assists",
    "first_qtr_rebounds": "1q rebounds",
    "first-quarter-rebounds": "1q rebounds",
    "first-quarter-assists": "1q assists",
    "first-quarter-points": "1q points",
    "3-pt": "three pointers made",
    "3-pointers made": "three pointers made",
    "made_three_pointers": "three pointers made",
    "three-made": "three pointers made",
    "3 pointers made": "three pointers made",
    "3-pt made": "three pointers made",
    "threes_made": "three pointers made",
    "3pa": "threes attempted",
    "3pm": "made threes",
    "3pt made": "made threes",
    "ast+reb": "assists + rebounds",
    "assists+rebounds": "assists + rebounds",
    "rebounds_and_assists": "assists + rebounds",
    "rebounds+assists": "assists + rebounds",
    "rebounds + assists": "assists + rebounds",
    "asts": "assists",
    "blks": "blocks",
    "dd": "double doubles",
    "double_doubles": "double doubles",
    "double-double": "double doubles",
    "def reb": "defensive rebounds",
    "fg": "field goals made",
    "fga": "field goals attempted",
    "attempted field goals": "field goals attempted",
    "ft": "free throws made",
    "fta": "free throws attempted",
    "ftm": "free throws made",
    "off reb": "offensive rebounds",
    "pts": "points",
    "pts+ast": "points + assists",
    "points+assists": "points + assists",
    "pa": "points + assists",
    "assists+points": "points + assists",
    "points_and_assists": "points + assists",
    "pts+reb": "points + rebounds",
    "points + rebounds": "points + rebounds",
    "points+rebounds": "points + rebounds",
    "pr": "points + rebounds",
    "points_and_rebounds": "points + rebounds",
    "assists+points+rebounds": "points + rebounds + assists",
    "pts+reb+ast": "points + rebounds + assists",
    "pts + rebs + asts": "points + rebounds + assists",
    "pts+rebs+asst": "points + rebounds + assists",
    "pts+rebs+asts": "points + rebounds + assists",
    "pts_reb_ast": "points + rebounds + assists",
    "pra": "points + rebounds + assists",
    "points + rebounds + assists": "points + rebounds + assists",
    "points_rebounds_assists": "points + rebounds + assists",
    "rebs": "rebounds",
    "stls": "steals",
    "td": "triple double",
    "to": "turnovers",
    ################# Football #################
    "anytime_touchdown": "anytime td",
    "def int": "defensive interceptions",
    "defensive ints": "defensive interceptions",
    "interceptions (def)": "defensive interceptions",
    "rushing touchdowns": "rushing tds",
    "rushing touchdown": "rushing tds",
    "fgm": "field goals made",
    "fg made": "field goals made",
    "interceptions thrown": "interceptions",
    "longest fg made yds (combo)": "longest field goal made yards (combo)",
    "int": "interceptions",
    "pass completions": "passing completions",
    "pass yards (combo)": "passing yards (combo)",
    "pass+rush yds": "passing + rushing yards",
    "pass + rush yards": "passing + rushing yards",
    "ints thrown": "interceptions",
    "kp": "kicking points",
    "kicker points": "kicking points",
    "passing touchdowns": "passing tds",
    "passing touchdown": "passing tds",
    "lpass comp": "longest passing completion",
    "longest pass": "longest passing completion",
    "longest pass completion": "longest passing completion",
    "lr": "longest reception",
    "longest catch": "longest reception",
    "lrun": "longest rush",
    "passing att": "passing attempts",
    "passing td": "passing tds",
    "passing yds": "passing yards",
    "receiving yds": "receiving yards",
    "rush+rec td": "rushing + receiving tds",
    "rush+rec tds": "rushing + receiving tds",
    "rushing att": "rushing attempts",
    "rushing yds": "rushing yards",
    "tack+ast": "tackles + assists",
    "rushing": "rushing yards",
    "pass att": "passing attempts",
    "pass comp": "passing completions",
    "completions": "passing completions",
    "fantasy pts": "fantasy points",
    "player fantasy score (prizepicks)": "fantasy points",
    "pass tds": "passing tds",
    "pass yards": "passing yards",
    "rec": "receiving",
    "rush + rec yards": "rushing + receiving yards",
    "rush + rec tds": "rushing + receiving tds",
    "rec yds": "receiving yards",
    "rec targets": "receiving targets",
    "targets": "receiving targets",
    "rec tds": "receiving tds",
    "rush": "rushing",
    "rush yards (combo)": "rushing yards (combo)",
    "rush att": "rushing attempts",
    "rush yards": "rushing yards",
    "rush tds": "rushing tds",
    "sacks": "sacks",
    "tackles": "tackles",
    "xp": "extra points made",
    "kicker extra points": "extra points made",
    "pat made": "passing attempts made",
    "xp made": "extra points made",
    "game high rec yards": "game high receiving yards",
    "game high rush yards": "game high rushing yards",
    "first td scorer": "1st td scorer",
    "first touchdown": "1st td scorer",
    "high receiving yards": "game high receiving yards",
    "high rushing yards": "game high rushing yards",
    "first completion (yards)": "first completion yards",
    "first reception (yards)": "first reception yards",
    "first rush attempt (yards)": "first rush attempt yards",
    "quarters with 1+ reception": "1+ reception in each quarter",
    "quarters with 10+ receiving yards": "10+ receiving yards in each quarter",
    "quarters with 2+ receptions": "2+ receptions in each quarter",
    "quarters with 5+ receiving yards": "5+ receiving yards in each quarter",
    "1h pass tds": "1h passing tds",
    "1h pass yards": "1h passing yards",
    "1h receptions": "1h receptions",
    "1h receiving yards": "1h receiving yards",
    "1q pass tds": "1q passing tds",
    "1q pass yards": "1q passing yards",
    "1q receptions": "1q receptions",
    "1q receiving yards": "1q receiving yards",
    "2h pass tds": "2h passing tds",
    "2h pass yards": "2h passing yards",
    "2h receptions": "2h receptions",
    "2h receiving yards": "2h receiving yards",
    "2q pass tds": "2q passing tds",
    "2q pass yards": "2q passing yards",
    "2q receptions": "2q receptions",
    "2q receiving yards": "2q receiving yards",
    "3q pass tds": "3q passing tds",
    "3q pass yards": "3q passing yards",
    "3q receptions": "3q receptions",
    "3q receiving yards": "3q receiving yards",
    "4q pass tds": "4q passing tds",
    "4q pass yards": "4q passing yards",
    "4q receptions": "4q receptions",
    "4q receiving yards": "4q receiving yards",

    ################## Hockey | Soccer ##################
    "assists": "assists",
    "fo won": "faceoffs won",
    "ga": "goals against",
    "goals": "goals",
    "hits": "hits",
    "ppp": "power play points",
    "goalie saves": "saves",
    "sog": "shots on goal",
    "toi": "time on ice",
    "Time On Ice (In Reg)": "time on ice",
    "goalkeeper saves": "saves",
    "assists + goals": "goals + assists",
    "player goals": "goals",
    "player assists": "assists",
    "player goals + assists": "goals + assists",
    ##################  Soccer ##################
    "shots": "shots attempted",
    "sot": "shots on target",
    "player dribble attempts": "dribble attempts",
    "player fouls": "fouls",
    "player cards": "cards",
    "player fouls drawn": "fouls drawn",
    "player offsides": "offsides",
    "player shots": "shots attempted",
    "player shots on target": "shots on target",
    "player tackles": "tackles",
    ################## Tennis ##################
    "breakpoints won": "break points won",
    "break-points-won": "break points won",
    "breakpts_won": "break points won",
    "total games lost": "games lost",
    "total games won": "games won",
    "total-games": "total games",
    "games_played": "total games",
    "games_won": "games won",
    "match total games": "total games",
    ################## Baseball ##################
    "rbi": "RBIs",
    "rbis": "RBIs",
    "rbi's": "RBIs",
    "hr": "home runs",
    "pitcher strikeouts": "strikeouts",
    "regular season  rbi's": "season RBIs",
    "season-rbis": "season RBIs",
    "regular season hits": "season hits",
    "season-hits": "season hits",
    "regular season home runs": "season home runs",
    "season-home-runs": "season home runs",
    "regular season stolen bases": "season stolen bases",
    "season-stolen-bases": "season stolen bases",
    "regular season strikeouts": "season strikeouts",
    "season-strikeouts": "season strikeouts",
    ################## Esports ##################
    "headshots on maps 1+2": "maps 1-2 headshots",
    "maps_1_and_2_headshots": "maps 1-2 headshots",
    "headshots_maps_1_2": "maps 1-2 headshots",
    "kills in game 1+2": "maps 1-2 kills",
    "kills on map 1+2": "maps 1-2 kills",
    "maps_1_and_2_kills": "maps 1-2 kills",
    "kills_maps_1_2": "maps 1-2 kills",
    "kills in map 1": "map 1 kills",
    "game-1-kills": "map 1 kills",
    "kills on map 1": "map 1 kills",
    "map_1_kills": "map 1 kills",
    "kills_map_1": "map 1 kills",
    "headshots_map_1": "map 1 headshots",
    "game-2-kills": "map 2 kills",
    "1st 2 maps assists": "maps 1-2 assists",
    "1st 2 maps kills": "maps 1-2 kills",
    "1st 2 maps headshots": "maps 1-2 headshots",
    "1st map kills": "map 1 kills",
    "1st map headshots": "map 1 headshots",
    "1st map assists": "map 1 assists",
    "2nd map kills": "map 2 kills",
    "2nd map headshots": "map 2 headshots",
    "2nd map assists": "map 2 assists",
    "1st 3 maps assists": "maps 1-3 assists",
    "1st 3 maps kills": "maps 1-3 kills",
    "1st 3 maps headshots": "maps 1-3 headshots",
    "1st 2 maps player kills": "maps 1-2 kills",
    "1st 2 maps player headshots": "maps 1-2 headshots",
    "kills": "maps 1-2 kills"
}


