LEAGUES = {
    "cs": "CS2",
    "counter-strike": "CS2",
    "league of legends": "LOL",
    "dota": "DOTA2",
    "dota pro circuit": "DOTA2",
    "lck": "LOL",
    "lcs": "LOL",
    'lec': "LOL",
    'lpl': "LOL",
    "leagueoflegends": "LOL",
    'valorant champions tour': "VAL",
    'valorant': "VAL",
    'eu lcs': "LOL",
    "mlbcombos": "MLB",
    "ncaaf": "CFB",
    "ncaafb": "CFB",
    "tennis m": "ATP",
    "tennis w": "WTA",
}

MARKET_TYPE_MAPPER = {
    "fg": "Full"
}

STAT_TYPES = {
    ################## Baseketball ##################
    "first_qtr_points": "1q points",
    "first_qtr_assists": "1q assists",
    "first_qtr_rebounds": "1q rebounds",
    "first-quarter-rebounds": "1q rebounds",
    "first-quarter-assists": "1q assists",
    "first-quarter-points": "1q points",
    "3-pt": "three pointers made",
    "3-pointers made": "three pointers made",
    "made_three_pointers": "three pointers made",
    "three-made": "three pointers made",
    "3 pointers made": "three pointers made",
    "3-pt made": "three pointers made",
    "threes_made": "three pointers made",
    "3pa": "threes attempted",
    "3pm": "made threes",
    "3pt made": "made threes",
    "ast+reb": "assists + rebounds",
    "assists+rebounds": "assists + rebounds",
    "rebounds_and_assists": "assists + rebounds",
    "rebounds+assists": "assists + rebounds",
    "rebounds + assists": "assists + rebounds",
    "asts": "assists",
    "blks": "blocks",
    "dd": "double doubles",
    "double_doubles": "double doubles",
    "double-double": "double doubles",
    "def reb": "defensive rebounds",
    "fg": "field goals made",
    "fga": "field goals attempted",
    "ft": "free throws made",
    "fta": "free throws attempted",
    "ftm": "free throws made",
    "off reb": "offensive rebounds",
    "pts": "points",
    "pts+ast": "points + assists",
    "points+assists": "points + assists",
    "pa": "points + assists",
    "assists+points": "points + assists",
    "points_and_assists": "points + assists",
    "pts+reb": "points + rebounds",
    "points + rebounds": "points + rebounds",
    "points+rebounds": "points + rebounds",
    "pr": "points + rebounds",
    "points_and_rebounds": "points + rebounds",
    "assists+points+rebounds": "points + rebounds + assists",
    "pts+reb+ast": "points + rebounds + assists",
    "pts + rebs + asts": "points + rebounds + assists",
    "pts+rebs+asst": "points + rebounds + assists",
    "pts+rebs+asts": "points + rebounds + assists",
    "pts_reb_ast": "points + rebounds + assists",
    "pra": "points + rebounds + assists",
    "points + rebounds + assists": "points + rebounds + assists",
    "points_rebounds_assists": "points + rebounds + assists",
    "rebs": "rebounds",
    "stls": "steals",
    "td": "triple double",
    "to": "turnovers",
    ################# Football #################
    "def int": "defensive interceptions",
    "fgm": "field goals made",
    "int": "interceptions",
    "kp": "kicking points",
    "lpass comp": "longest passing completion",
    "lr": "longest reception",
    "lrun": "longest rush",
    "pass att": "passing attempts",
    "pass comp": "passing completions",
    "pass tds": "passing tds",
    "pass yards": "passing yards",
    "rec": "receiving",
    "rec yds": "receiving yards",
    "rec tds": "receiving tds",
    "rush": "rushing",
    "rush att": "rushing attempts",
    "rush yards": "rushing yards",
    "rush tds": "rushing tds",
    "sacks": "sacks",
    "tackles": "tackles",
    "xp": "extra points made",
    ################## Hockey ##################
    "assists": "assists",
    "fo won": "faceoffs won",
    "ga": "goals against",
    "goals": "goals",
    "hits": "hits",
    "ppp": "power play points",
    "goalie saves": "saves",
    "sog": "shots on goal",
    "toi": "time on ice",
    "Time On Ice (In Reg)": "time on ice",
    ################## Tennis ##################
    "breakpoints won": "break points won",
    "break-points-won": "break points won",
    "total games lost": "games lost",
    "total games won": "games won",
    "total-games": "total games",
    ################## Baseball ##################
    "rbi": "RBIs",
    "rbis": "RBIs",
    "rbi's": "RBIs",
    "hr": "home runs",
    "pitcher strikeouts": "strikeouts",
    "regular season  rbi's": "season RBIs",
    "season-rbis": "season RBIs",
    "regular season hits": "season hits",
    "season-hits": "season hits",
    "regular season home runs": "season home runs",
    "season-home-runs": "season home runs",
    "regular season stolen bases": "season stolen bases",
    "season-stolen-bases": "season stolen bases",
    "regular season strikeouts": "season strikeouts",
    "season-strikeouts": "season strikeouts",
    ################## Esports ##################
    "headshots on maps 1+2": "maps 1-2 headshots",
    "maps_1_and_2_headshots": "maps 1-2 headshots",
    "headshots_maps_1_2": "maps 1-2 headshots",
    "kills in game 1+2": "maps 1-2 kills",
    "kills on map 1+2": "maps 1-2 kills",
    "maps_1_and_2_kills": "maps 1-2 kills",
    "kills_maps_1_2": "maps 1-2 kills",
    "kills in map 1": "map 1 kills",
    "game-1-kills": "map 1 kills",
    "kills on map 1": "map 1 kills",
    "map_1_kills": "map 1 kills",
    "kills_map_1": "map 1 kills",
    "headshots_map_1": "map 1 headshots",
    "game-2-kills": "map 2 kills",
    "1st 2 maps assists": "maps 1-2 assists",
    "1st 2 maps kills": "maps 1-2 kills",
    "1st 2 maps headshots": "maps 1-2 headshots",
    "1st map kills": "map 1 kills",
    "1st map headshots": "map 1 headshots",
    "1st map assists": "map 1 assists",
    "2nd map kills": "map 2 kills",
    "2nd map headshots": "map 2 headshots",
    "2nd map assists": "map 2 assists",
    "1st 3 maps assists": "maps 1-3 assists",
    "1st 3 maps kills": "maps 1-3 kills",
    "1st 3 maps headshots": "maps 1-3 headshots",
    "1st 2 maps player kills": "maps 1-2 kills",
    "1st 2 maps player headshots": "maps 1-2 headshots",
    "kills": "maps 1-2 kills"
}


