BETVEGAS_LEAGUE_MAPPER = {
    # --------------------- HOCKEY / NHL ---------------------
    "nhl - regulation time (no overtime)": "NHL",
    "nhl - stanley cup - odds to win": "NHL STANLEY CUP FUTURES",
    "nhl - conference - odds to win": "NHL CONFERENCE FUTURES",
    "nhl - divisions - odds to win": "NHL DIVISION FUTURES",
    "hockey - ncaa men championship": "NCAA HOCKEY MEN",
    "nhl - time of 1st goal (1st period)": "NHL",
    "national hockey league": "NHL",
    "nhl - grand salami": "NHL",
    "nhl periods": "NHL",
    "ncaa hockey - women (ot + so)": "NCAA HOCKEY WOMEN",
    "ncaa hockey - men (ot + so)": "NCAA HOCKEY MEN",
    "hockey - czech republic - (no overtime)": "CZECH EXTRALIGA",
    "hockey - finland -  (no overtime)": "FINNISH LIIGA",
    "nhl - team totals game": "NHL",
    "nhl - player props shots on goal": "NHL",
    "hk - canada - ontario hockey league (+ot)": "ONTARIO HOCKEY LEAGUE",
    "hk - belarus - extraleague": "BELARUS EXTRALIGA",
    "hk - usa - echl + ot": "ECHL",
    "hk -russia-khl": "KHL",
    "hk - russia - magnitka open": "KHL MAGNITKA OPEN",
    "hockey - norway-eliteserien (no ot)": "NORWAY ELITESERIEN",
    "hockey - france-ligue magnus (no ot)": "LIGUE MAGNUS",
    "hockey - germany-del 2 (no ot)": "DEL 2",
    "hockey - sweden - swedish hockey league (no ot)": "SHL",
    "hockey - slovakia-extraliga (no ot)": "SLOVAK EXTRALIGA",
    "hockey - germany-del (no ot)": "DEL",
    "hockey - poland-polish hockey league (no ot)": "POLISH HOCKEY LEAGUE",
    "hockey - switzerland - nla (no ot)": "NLA",
    "hockey - denmark-metal ligaen (no ot)": "METAL LIGAEN",
    "hk - europe champions league": "CHAMPIONS HOCKEY LEAGUE",
    "nhl - player props - shots on goal": "NHL",
    "nhl - adjusted puck lines": "NHL",
    "nhl props": "NHL",
    "nhl - player props - total points": "NHL",

    # --------------------- SOCCER ---------------------
    "english premier league": "PREMIER LEAGUE",
    "spain la liga": "LA LIGA",
    "italian serie a": "SERIE A",
    "germany - 1st bundesliga": "BUNDESLIGA",
    "france ligue 1": "LIGUE 1",

    "soc - russia - premiere league": "RUSSIAN PREMIER LEAGUE",
    "soc - denmark - superligaen": "DANISH SUPERLIGA",
    "soc - norway - eliteserien": "NORWEGIAN ELITESERIEN",

    "soc - england - league one": "EFL LEAGUE ONE",
    "soc - austria - 2. liga": "AUSTRIA 2. LIGA",
    "soc - germany - regional liga nordost": "REGIONALLIGA NORDOST",
    "soc - sweden - superettan": "SUPERETTAN",
    "soc - england - northern league division one": "NORTHERN LEAGUE DIVISION ONE",
    "soc - switzerland - 1. liga promotion": "SWISS 1. LIGA PROMOTION",
    "soc - france - national 1": "CHAMPIONNAT NATIONAL",
    "soc - germany -regional liga west": "REGIONALLIGA WEST",
    "soc - england - national league north": "NATIONAL LEAGUE NORTH",
    "soc - romania - liga 2": "LIGA II",
    "soc - bulgaria second professional ft league": "BULGARIA SECOND LEAGUE",
    "soc - germany - dfb pokal": "DFB POKAL",
    "soc - portugal - segunda liga": "LIGA PORTUGAL 2",
    "soc - lithuania - i lyga": "I LYGA",
    "soc - england - efl cup": "EFL CUP",
    "soc - belarus - vysshaya liga": "BELARUSIAN PREMIER LEAGUE",
    "soc - germany - regionalliga sudwest": "REGIONALLIGA SÜDWEST",
    "soc - england - national league": "NATIONAL LEAGUE",
    "soc - ukraine - premier league": "UKRAINIAN PREMIER LEAGUE",
    "soc - poland - 1 liga": "I LIGA",
    "soc - scotland - scotland championship": "SCOTTISH CHAMPIONSHIP",
    "soc - switzerland -  challenge league": "SWISS CHALLENGE LEAGUE",
    "soc - switzerland -  super league": "SWISS SUPER LEAGUE",
    "soc - germany - 3. liga": "3. LIGA",
    "soc - norway - obos-ligaen": "OBOS-LIGAEN",
    "soc - germany - regionalliga north": "REGIONALLIGA NORD",
    "soc - england - isthmian league premier": "ISTHMIAN LEAGUE PREMIER",
    "soc - england -southern premier league central": "SOUTHERN PREMIER CENTRAL",
    "soc - england - national league south": "NATIONAL LEAGUE SOUTH",
    "soc - england - northern premier league": "NORTHERN PREMIER LEAGUE",
    "soc - estonia - meistriliiga": "MEISTRILIIGA",
    "soc - england - the championship": "EFL CHAMPIONSHIP",
    "soc - armenia - premier league": "ARMENIAN PREMIER LEAGUE",
    "soc - poland - ekstraklasa": "EKSTRAKLASA",
    "soc - poland - 2 liga": "II LIGA",
    "soc - england - professional development league": "PROFESSIONAL DEVELOPMENT LEAGUE",
    "soc - germany - regionalliga bayern": "REGIONALLIGA BAYERN",
    "soc - poland - league 3": "III LIGA",
    "soc - russia - fnl": "RUSSIAN FIRST LEAGUE",
    "soc - northern ireland - premier league": "NIFL PREMIERSHIP",
    "soc - serbia - superliga": "SERBIAN SUPERLIGA",
    "soc - romania - liga 1": "LIGA I",
    "soc - germany - oberliga": "OBERLIGA",
    "soc - england - southern league premier south": "SOUTHERN PREMIER SOUTH",
    "soc - spain - laliga2": "SEGUNDA DIVISIÓN",
    "soc - denmark - 1st division": "DANISH 1ST DIVISION",
    "soc - bulgaria - parva first league": "BULGARIAN FIRST LEAGUE",
    "soc - italy - coppa italia": "COPPA ITALIA"
}
